x-fastapi: &fastapi
  image: local/fastapi:latest
  build:
    context: docker-resources/fastapi
  working_dir: /app
  healthcheck:
    test: "curl -f http://localhost:8000/health || exit 1"
    interval: 10s
    timeout: 5s
    retries: 5

services:
  line-racing:
    image: nginx:alpine3.18
    volumes:
      - ./dist:/usr/share/nginx/html:cached
      - ./docker-resources/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8000:8000
    depends_on:
      player1:
        condition: service_healthy
      player2:
        condition: service_healthy
      player3:
        condition: service_healthy
      player4:
        condition: service_healthy
      player5:
        condition: service_healthy
  player1:
    image: local/echo-player1:latest
    build:
      context: docker-resources/player1
    volumes:
      - ./docker-resources/player1:/go/src/app:cached
    ports:
      - 8001:8000
    healthcheck:
      test: "curl -f http://localhost:8000/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
  player2:
    build:
      context: docker-resources/player2
    working_dir: /app
    healthcheck:
      test: "curl -f http://localhost:8000/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8002:8000
  player3:
    <<: *fastapi
    volumes:
      - ./docker-resources/player3:/app:cached
    ports:
      - 8003:8000
  player4:
    <<: *fastapi
    volumes:
      - ./docker-resources/player4:/app:cached
    ports:
      - 8004:8000
  player5:
    <<: *fastapi
    volumes:
      - ./docker-resources/player5:/app:cached
    ports:
      - 8005:8000
